export const GET_MIXED_QUOTES = 'GET_MIXED_QUOTES';
export const QUOTE_COUNTER = 'QUOTE_COUNTER';
export const SOLO_SELECTION = 'SOLO_SELECTION';
export const MIX_SELECTION = 'MIX_SELECTION';
export const NEXT_QUOTE = 'NEXT_QUOTE';
export const NEXT_QUOTE_UPDATE_COUNTER = 'NEXT_QUOTE_UPDATE_COUNTER';
export const CHECK_AND_DO = 'CHECK_AND_DO';
export const SET_LOADING = 'SET_LOADING';
export const RESET_COUNTER = 'RESET_COUNTER';
export const BUTTON_TEXT_ONE = 'BUTTON_TEXT_ONE';
export const BUTTON_TEXT_TWO = 'BUTTON_TEXT_TWO';
export const BUTTON_TEXT_THREE = 'BUTTON_TEXT_THREE';
export const ALL_QUOTES_SOLVED = 'ALL_QUOTES_SOLVED';




